# Generated by Django 5.2.2 on 2025-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_concepts', models.JSONField()),
                ('learning_materials', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_final_quiz', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answers', models.JSONField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('weak_concepts', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.learningpath')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
                ('final_quiz_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_attempt', to='learning.userquizattempt')),
                ('initial_quiz_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_attempt', to='learning.userquizattempt')),
            ],
        ),
    ]
